---
-
  name: 'Attack +0'
  attack: 0
  starting_count: 6
-
  name: 'Attack +1'
  attack: 1
  starting_count: 5
-
  name: 'Attack -1'
  attack: -1
  starting_count: 5
-
  name: 'Attack +2'
  attack: 2
  starting_count: 1
-
  name: 'Attack -2'
  attack: -2
  starting_count: 1
- &crit_miss
  name: 'Null'
  attack: 0
  starting_count: 1
  shuffle: true
  miss: true
- &crit_hit
  name: '2x'
  attack: 0
  starting_count: 1
  shuffle: true
  crit: true
-
  <<: *crit_miss
  name: 'Curse'
  shuffle: false
  starting_count: 0
-
  <<: *crit_hit
  name: 'Bless'
  shuffle: false
  starting_count: 0
-
  name: 'Attack +3'
  attack: 3
-
  name: 'Rolling Attack +1'
  attack: 1
  rolling: true
-
  name: 'Rolling Muddle'
  attack: 0
  rolling: true
  muddle: true
-
  name: 'Rolling Push 1'
  attack: 0
  rolling: true
  push: 1
-
  name: 'Rolling Pierce 3'
  attack: 0
  rolling: true
  pierce: 3
-
  name: 'Rolling Stun'
  attack: 0
  rolling: true
  stun: true
-
  name: 'Rolling Disarm'
  attack: 0
  rolling: true
  disarm: true
-
  name: 'Rolling Muddle'
  attack: 0
  rolling: true
  muddle: true
-
  name: 'Rolling Add Target'
  attack: 0
  rolling: true
  add_target: true
-
  name: 'Attack +1 Shield 1'
  attack: 1
  shield: 1
-
  name: 'Attack +1 Wound'
  attack: 1
  wound: true
-
  name: 'Attack +1 Immobilize'
  attack: 1
  immobilize: true
-
  name: 'Attack +1 Heal +2'
  attack: 2
  heal: 2
-
  name: 'Attack +0 Add Target'
  attack: 0
  add_target: true
-
  name: 'Ignore negative scenario effects'
-
  name: 'Attack +0 Stun'
  attack: 0
  stun: true
-
  name: 'Attack +0 Curse'
  attack: 0
  curse: true
-
  name: 'Attack +2 Fire'
  attack: 2
  fire: true
-
  name: 'Attack +2 Ice'
  attack: 2
  ice: true
-
  name: 'Rolling Fire'
  rolling: true
  fire: true
-
  name: 'Rolling Nature'
  rolling: true
  nature: true
-
  name: 'Rolling Wind'
  rolling: true
  wind: true
-
  name: 'Rolling Ice'
  rolling: true
  ice: true
-
  name: 'Rolling Sun'
  rolling: true
  sun: true
-
  name: 'Rolling Night'
  rolling: true
  night: true
-
  name: 'Rolling Poison'
  rolling: true
  poison: true
-
  name: 'Rolling Invisible'
  rolling: true
  invisible: true
-
  name: 'Attack +2 Muddle'
  attack: 2
  muddle: true
-
  name: 'Rolling Push 2'
  rolling: true
  push: 2