---
brute:
  perks:
    remove_two_minus_one_cards: 1
    replace_one_minus_one_card_with_one_plus_one_card: 1
    add_two_plus_one_cards: 2
    add_one_plus_three_card: 1
    add_three_rolling_push_one_cards: 2
    add_two_rolling_pierce_three_cards: 1
    add_one_rolling_stun_card: 2
    add_one_rolling_disarm_card_and_one_rolling_muddle_card: 1
    add_one_rolling_add_target_card: 2
    add_one_plus_one_shield_one_self_card: 1
    ignore_negative_item_effects_and_add_one_plus_one_card: 1
tinkerer:
  perks:
    remove_two_minus_one_cards: 2
    replace_one_minus_two_card_with_one_plus_zero_card: 1
    add_two_plus_one_cards: 1
    add_one_plus_three_card: 1
    add_two_rolling_fire_cards: 1
    add_three_rolling_muddle_cards: 1
    add_one_plus_one_wound_card: 2
    add_one_plus_one_immobilize_card: 2
    add_one_plus_one_heal_plus_two_card: 2
    add_one_plus_zero_add_target_card: 1
    ignore_negative_scenario_effects: 1