---
beast_tyrant:
  perks:
berserker:
  perks:
brute:
  perks:
    remove_two_minus_one_cards: 1
    replace_one_minus_one_card_with_one_plus_one_card: 1
    add_two_plus_one_cards: 2
    add_one_plus_three_card: 1
    add_three_rolling_push_one_cards: 2
    add_two_rolling_pierce_three_cards: 1
    add_one_rolling_stun_card: 2
    add_one_rolling_disarm_card_and_one_rolling_muddle_card: 1
    add_one_rolling_add_target_card: 2
    add_one_plus_one_shield_one_self_card: 1
    ignore_negative_item_effects_and_add_one_plus_one_card: 1
cragheart:
  perks:
    remove_four_plus_zero_cards: 1
    replace_one_minus_one_card_with_one_plus_one_card: 3
    add_one_minus_two_card_and_two_plus_two_cards: 1
    add_one_plus_one_immobilize_card: 2
    add_one_plus_two_muddle_card: 2
    add_two_rolling_push_two_cards: 1
    add_two_rolling_nature_cards: 2
    add_two_rolling_wind_cards: 1
    ignore_negative_item_effects: 1
    ignore_negative_scenario_effects: 1
doomstalker:
  perks:
elementalist:
  perks:
mindthief:
  perks:
    remove_two_minus_one_cards: 2
    remove_four_plus_zero_cards: 1
    replace_two_plus_one_cards_with_two_plus_two_cards: 1
    replace_one_minus_two_card_with_one_plus_zero_card: 1
    add_one_plus_two_ice_card: 2
    add_two_rolling_plus_one_cards: 2
    add_three_rolling_pull_one_cards: 1
    add_three_rolling_muddle_cards: 1
    add_two_rolling_immobilize_cards: 1
    add_one_rolling_stun_card: 1
    add_one_rolling_disarm_card_and_one_rolling_muddle_card: 1
    ignore_negative_scenario_effects: 1
nightshroud:
  perks:
    remove_two_minus_one_cards: 2
    remove_four_plus_zero_cards: 1
    add_one_minus_one_dark_card: 2
    replace_one_minus_one_dark_card_with_one_plus_one_dark_card: 2
    add_one_plus_one_invisible_card: 2
    add_three_rolling_muddle_cards: 2
    add_two_rolling_heal_plus_one_cards: 1
    add_two_rolling_curse_cards: 2
    add_one_rolling_add_target_card: 1
    ignore_negative_scenario_effects_and_add_two_plus_one_cards: 1
plagueherald:
  perks:
quartermaster:
  perks:
    remove_two_minus_one_cards: 2
    remove_four_plus_zero_cards: 1
    replace_one_plus_zero_card_with_one_plus_two_card: 2
    add_two_rolling_plus_one_cards: 2
    add_three_rolling_muddle_cards: 1
    add_two_rolling_pierce_three_cards: 1
    add_one_rolling_stun_card: 1
    add_one_rolling_add_target_card: 1
    add_one_plus_zero_refresh_an_item_card: 3
    ignore_negative_item_effects_and_add_two_plus_one_cards: 1
sawbones:
  perks:
scoundrel:
  perks:
    remove_two_minus_one_cards: 2
    remove_four_plus_zero_cards: 1
    replace_one_minus_two_card_with_one_plus_zero_card: 1
    replace_one_minus_one_card_with_one_plus_one_card: 1
    replace_one_plus_zero_card_with_one_plus_two_card: 2
    add_two_rolling_plus_one_cards: 2
    add_two_rolling_pierce_three_cards: 1
    add_two_rolling_poison_cards: 2
    add_two_rolling_muddle_cards: 1
    add_one_rolling_invisible_card: 1
    ignore_negative_scenario_effects: 1
soothsinger:
  perks:
spellweaver:
  perks:
    remove_four_plus_zero_cards: 1
    replace_one_minus_one_card_with_one_plus_one_card: 2
    add_two_plus_one_cards: 2
    add_one_plus_zero_stun_card: 1
    add_one_plus_one_wound_card: 1
    add_one_plus_one_immobilize_card: 1
    add_one_plus_one_curse_card: 1
    add_one_plus_two_fire_card: 2
    add_one_plus_two_ice_card: 2
    add_one_rolling_nature_and_one_rolling_wind_card: 1
    add_one_rolling_light_and_one_rolling_dark_card: 1
summoner:
  perks:
    remove_two_minus_one_cards: 1
    replace_one_minus_two_card_with_one_plus_zero_card: 1
    replace_one_minus_one_card_with_one_plus_one_card: 3
    add_one_plus_two_card: 2
    add_two_rolling_wound_cards: 1
    add_two_rolling_poison_cards: 1
    add_two_rolling_heal_plus_one_cards: 3
    add_one_rolling_fire_and_one_rolling_wind_card: 1
    add_one_rolling_dark_and_one_rolling_nature_card: 1
    ignore_negative_scenario_effects_and_add_two_plus_one_cards: 1
sunkeeper:
  perks:
    remove_two_minus_one_cards: 2
    remove_four_plus_zero_cards: 1
    replace_one_minus_two_card_with_one_plus_zero_card: 1
    replace_one_plus_zero_card_with_one_plus_two_card: 1
    add_two_rolling_plus_one_cards: 2
    add_two_rolling_heal_plus_one_cards: 2
    add_one_rolling_stun_card: 1
    add_two_rolling_light_cards: 2
    add_two_rolling_shield_1_self_cards: 1
    ignore_negative_item_effects_and_add_two_plus_one_cards: 1
    ignore_negative_scenario_effects: 1
tinkerer:
  perks:
    remove_two_minus_one_cards: 2
    replace_one_minus_two_card_with_one_plus_zero_card: 1
    add_two_plus_one_cards: 1
    add_one_plus_three_card: 1
    add_two_rolling_fire_cards: 1
    add_three_rolling_muddle_cards: 1
    add_one_plus_one_wound_card: 2
    add_one_plus_one_immobilize_card: 2
    add_one_plus_one_heal_plus_two_card: 2
    add_one_plus_zero_add_target_card: 1
    ignore_negative_scenario_effects: 1